sudo: required

services:
  - docker

before_install:
  - docker build -t nagendravarma428/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nagendravarma428/docker-react npm run test